```{r, echo=FALSE, cache=FALSE }
set_parent("thesis.Rmd")
```

\chapter{Conclusion}

\section{Introduction}

As stated in chapter one, the primary goal of this research was re-evaluating the conventional rice-centered models in order to better understand the overall pattern of subsistence strategy in the period of transition from hunter-gatherers to farmers and assess the weight of rice in it. To achieve this goal the study (1) tests the hypothesis that a wide range of resources were utilized along with rice between 3,400 and 2,000 BP., and (2) establishes a general chronology of subsistence during this period, incorporating in that work the organic geochemical analysis and luminescence dating of the pottery excavated from four large inland habitation sites in the central part of the Korean Peninsula. In this last chapter I will review each chapter of this thesis and show how they fulfilled the goals mentioned just above. 

\section{Reprising the work so far}

In chapter one, I briefly reviewed recent approaches to understanding the subsistence change from foragers to farmers. Several underlying characteristics that the places showing the evidence of farming have in common were also mentioned. These characteristics include (1) opportunistic migrations of small groups of people, (2) ambiguity in the results of the genetic studies, and (3) selective adaptation of new subsistence strategy. Then, I elucidated the main purpose of this thesis by narrowing down the region investigated to the central part of the Korean Peninsula and addressing the current ideas that Korean archaeologists have on the role of the intensive rice agriculture among them. 

In chapter two, firstly, the general history and social context of Korean archaeology from its beginning stage to the present time was stated, focusing especially on the political upheavals such as the Japanese annexation of the country and the Korean War. Then, I showed the cultural historical background of the two main prehistoric periods in question: the Chulmun and Mumun periods. After that, I discussed current views on the transition from foragers to farmers in the Korean Peninsula and its main problematic assumption: strict dichotomy between Chulmun hunter-gatherers and Mumun full-dress rice farmers. Lastly, the central hypothesis of this thesis—that there was utilization of a wide range of animal and plant resources along with rice among the ancient farmers in the central part of the Korean Peninsula—was proposed based on the recent scientific evidence from Korea and Europe. 

Chapters three and four were dedicated respectively to the two main analytical methods of this thesis: luminescence dating and organic geochemical analyses. In these chapters, I discussed the methods, research design and analytical procedure of the luminescence dating and organic geochemical analysis. I briefly outlined the history of the two methods employed in the discipline of archaeology, elucidated some of their main principles and emphasized why these two methods are essential to achieve my goal. Also, some of the important implications related to the methods were listed. Lastly, the details of the laboratory experimental procedures were elucidated.    

In the fifth chapter of this thesis, I presented the results of the luminescence dating the organic geochemical analyses on the four inland habitation sites (Sosa-Dong, Kimpo-Yangchon, Songguk-Ri, Eupha-Ri). Firstly, I did an in-depth review of the overall archaeological records of the four sites. Then, the sampling strategy, methods and the results of the organic geochemical analyses and luminescence dating for each of the sites were elucidated one by one. For the interpretation of the data that were produced by the two methods, available archaeological records and radiocarbon dates were incorporated, because this type of scientific research can be strengthen by the proper archaeological contextual information.  

In chapter six, I further examined the initial interpretations that I had made in the former chapter with the available bulk isotope and paleobotanical data. First, I re-evaluated the current rice-base model and its problematic assumption of the strict dichotomy between Chulmun hunter-gatherers and Mumun full-dress rice farmers by presenting the possibility of continuity between the Chulmun and the Mumun periods. I also tried to interpret the dichotomy/continuity between the Chulmun and the Mumun periods with the concept of essentialism versus materialism. Then, by correlating the results of the organic geochemical analyses and luminescence dating with the available bulk isotope and paleobotanical data, I suggested hunting and fishing continued after the introduction of rice farming. Also, by revealing the relative proportion of C3 plant oil in the entire identified food classes, I emphasized the minor role of rice as a subsistence strategy during the Mumun period. Lastly, I listed some of the important implications of the results in this thesis.

\section{Transition from foraging to farming: Theoretical model vs. Empirical world }

Now I have the results in hand, I will return to the issue raised in chapter one of what the most important factors are in explaining the emergence of agriculture. As I mentioned in chapter one, recent approaches to understanding the subsistence change from foragers to farmers could fall into four categories: (1) population pressure, (2) climatic fluctuation, (3) cultural or social processes, and (4) evolutionary processes. The population pressure model, climatic fluctuation model, and evolutionary model usually assume external stresses and emphasize the capacity of farming as a stress reliever. In these models, people use agriculture as a risk-reduction strategy against resource stress driven by environmental changes. Recently, in Korean archaeology, there is a heated debate over the evidence of external stresses (e.g. population increase or sea level change) around 4,000–3,000 BP and the introduction of rice farming as a stress reliever [cf. @Bae2013; @Kim2003; -@Kim2006b; @Kim2010b; @Lee2001; @Lee2011b; @Shimoyama1999]. However, the suggested evidence of resource stress driven by environmental change is still limited and requires further investigation. 

Above all, in the Korean Peninsula, if rice agriculture was used as a risk-reduction strategy, rice should be the mainstay of the Korean diet from the Mumun period. However, according to the results of the organic geochemical analyses on the potsherds from major habitation sites such as Sosa-Dong, Kimpo-Yangchon and Songguk-Ri, hunted wild animals and marine resources were a significant part of the Mumun farmers' day to day foodstuffs. Though the results from Songguk-Ri indicated the possibility of rice as one of the main subsistence resources (see chapter five), the site is almost 1,000 years later (2,500 BP; cf. Table \ref{tab:radiocarbon_SG}) than when the intensive rice agriculture first initiated (ca. 3,400 BP).  This means the Mumun subsistence pattern does not support those models based on the external stresses. The cultural or social model does not convincingly explain the Mumun subsistence either, for the evidence of conceptual ideas such as a new cosmology, religious practices, symbolic behaviors or a wide range of information in relation to rice farming is not clear. 

The subsistence pattern we can reveal from the results of the organic geochemical analyses in this thesis and the limited (or controversial) evidence related to the resource stress suggest that the Korean Peninsula might have been a relatively stable/rich resource zone by the time of the transition from foraging to farming. Interestingly, in East Asia, we do observe similar patterns. For example, the Yangtze River Valley corridor in China, where we can find the earliest evidence of rice agriculture in the world, was a very rich resource zone [@Silva2015; @Smith1998; @Smith2007]. Also, Jomon Japan, the period that is traditionally considered as giving an affluent hunter-gathering context, showed solid evidence of plant domestication [@Obata2007]. In none of these areas did domestication of plants and agriculture appear to have developed within a necessity is the mother of invention context [@Smith2007: p. 197]. Then, why can we observe the initiation of agriculture in these rich resource zones? 

This resource rich context for the initial domestication of plants and development of agriculture fits with the expectations of the niche-construction theory [@Laland2001; @Laland2006; @Odling-Smee2003]. The niche construction is defined as organism-driven environmental modification and activities of organisms that bring about changes in environment. From this point of view, not only does an environment cause changes in species through selection, but species also cause changes in their environment through niche construction. This means, within this theoretical framework, it is possible that an organism can actively change its environment for their own purposes without experiencing other causal factors. Humans are acknowledged to be the ultimate niche constructors, both in terms of the diversity of different ways in which we manipulate the environment around us for our own benefits and the magnitude of our resultant impacts [@Smith2007: p. 195]. In this perspective, agriculture can be one of the pinnacles of human niche construction (i.e. the modification of a species' environment by members of that species to fit their own ends). The evidence from Japan and China showed that domestication of plants and agriculture developed within rich resource conditions that enable the continuous human experimental intervention in the environment. According to niche-construction theory, the rich resource zones, those that exhibited a greater capacity for supporting more people in more permanent settlements, could be expected to have witnessed stronger sustained niche-construction efforts [cf. @Odling-Smee2003]. The wider the range of species included in human efforts of intervention became, and the more different potential forms of intervention human could attempt, the greater the likelihood of domestication and agriculture would have been successful [@Smith2007]. 

Then, what was the motivation for the ancient Koreans to create their own niche through practicing rice agriculture? As I mentioned in Chapter two, it was the increased sedentism [@Price1995a: p. 8]. The evidence from Japan and China also showed that before the initial domestication of plants and development of agriculture, hunter-gatherers started to take the sedentary life style [@Smith1998; @Smith2007;  @Crawford2011]. According to Bar-Yosef [@Rocek1998] the non-agricultural sedentism requires storage technologies and containers such as pottery or special pits in which to store food securely. Also, it requires sufficient year-round, easily accessible local natural resources. In the Korean Peninsula, we have solid evidence of a long-term, permanent occupation of the peninsula by complex hunter-gatherers at various places since around 6,000 BP. At the Amsa-Dong Site in south-east Seoul  (Figure \ref{site_locations}), at least 12 houses, a significant amount of pottery and different types of ground stone tools such as arrow points, spear points and sickles, were excavated [@Im1985]. The house structures and seasonality of the faunal assemblages at the Tongsam-Dong site (Figure \ref{site_locations}) in the southern part of the Korean Peninsula indicate that people lived there year-round on a permanent basis [@Lee2001]. In this sedentary life style, along with hunting and gathering, prehistoric Koreans already had specific subsistence solutions which included distinctive combinations of wild (e.g. acorn, Manchurian walnut), possibly managed (e.g. chenopod, panicoid grass), and domesticated (e.g. foxtail and broomcorn millet, possibly soybean, azuki and beefsteak plant) plants from 5,500 BP [@Lee2011b: p. S326]. The prehistoric Koreans created their niche long before the initiation of rice agriculture. Rice agriculture was just an another addition of environment engineering (niche construction) to get a more reliable resource.  

The transitions from foragers to farmers that occurred around the world had various and diverse pathways and probably cannot be fully explained with a few generalized models. This diversity motivates us to investigate the specific manifestations of this transition in different parts of the world and better understand the different ways that people made this profound transformation. In the central  part of the prehistoric Korean Peninsula, from the beginning of the Mumun period (c.a. 3,400 BP) we observe the solid evidence of the intensive rice farming. However, even after rice farming was introduced, people still relied on hunting and gathering of both terrestrial animals and marine resources. In the central part of the Korean Peninsula, the indigenous foragers adopted new subsistence strategies little by little for their own purposes [cf. @Crawford2011; @Lee2011b; @Robb2013; @Smith1995; -@Smith2007; -@Smith2011].   

\section{Concluding remarks: The role of the intensive rice agriculture as a subsistence strategy in the prehistoric Korean Peninsula}

In this thesis I focused on the four inland habitation sites (Sosa-Dong, Kimpo-Yangchon, Songguk-Ri, Eupha-Ri) in the central part of the Korean Peninsula, a region that contains a vast amount of archaeological materials related to the subsistence change in the deep past. The aim of this research was re-evaluating the conventional rice-centered models to better understand the overall pattern of subsistence strategies and assess the weight of rice in it. To achieve this goal the study tested the central hypothesis that a wide range of resources were utilized along with rice between 3,400 and 2,000 BP. The results of the organic geochemical analyses on the potsherds from the four sites supported the suggested hypothesis, indicating that most of the pots were used for processing terrestrial animals and marine resources.

In the central Korean Peninsula, past efforts to reconstruct the ancient dietary patterns have been challenged by the high acidity of the sediments (RDA 1988). Because of these acidic sediments, the direct examination of the remains of subsistence resources in the Korean Peninsula is limited to relatively special locations that provide better preservation of bone or plant remains such as caves, rock-shelters, or shell middens [cf. @Choy2009; -@Choy2010; -@Choy2012]. 

In terms of archaeological records, it is clear that the intensive agriculture was practiced in the central part of the Korean Peninsula as early as around 3,400 BP [@Lee2003; -@Lee2011b]. Solid evidence of dry fields, irrigated rice paddies and harvesting tools have been found [@Yoon2010]. During this period, many large scale inland villages started to appear. However, most of these sites did not yield paleobotanical evidence and faunal remains due to post-depositional processes and the high acidity of the archaeological sediments. Due to these conditions, Korean archaeologists are not able to recover detailed information about the diet of the ancient Korean farmers, and the main focus has been put on harvested crops such as rice [@Kim2006; cf. @Lee2011b]. 

The subsistence change related to the emergence of agriculture always has been the critical part of anthropological debates. This subsistence change has been often described as a transition from hunter gathering to intensive agriculture. However, in many areas, scholars have only focused on how quickly or completely people abandoned wild terrestrial and marine resources after the introduction of domesticated plants [cf. @Craig2011]. Once the domesticated plants are introduced, the role of other food resources in the ancient farmers’ diet is neglected. In the Korean archaeology, rice has been often considered as a dominant subsistence resource since 3,400 BP. The possibility of other subsistence strategies in those farmers’ diet, for example, hunting terrestrial animals and procuring aquatic resources, were largely undermined. 

However, the results of the organic geochemical analyses and luminescence dating suggest that both terrestrial and aquatic animals were a considerable part of the ancient farmers’ diet, well after farming was introduced. It is unquestionable that the intensive rice agriculture was practiced in the Korean Peninsula as early as 3,400 BP. However, the results of this thesis indicated that there was a wider range of resource utilization and the role of rice was somewhat limited. What is overlooked in the subsistence studies of the prehistoric Korea is the distinction between the first adoption of crops and the later development of the intensive agriculture [@Lee2011b]. The migrants [cf. @Kim2006b] probably needed time to adjust themselves to the local environmental conditions, particularly for rice agriculture, which required complicated irrigation techniques and intensive labor effort. Though rice was considered as ‘cure all remedy' [@Lee2011b: p. S327] that solves various resource stresses around 3400 BP and additionally argued to be a driving factor of the social complexity by the Songguk-Ri stage (the Middle Mumun period), it may have played a relatively minor subsistence role during this period.
